### ISSUE TITLE
Bug when configuring AddOns

### ISSUE THREAD

**Issue by turbocell** [cogwerkz/gUI4#26]
Using GUI with a handful of other addons. Clicking a drop down menu in the settings for any other addon does nothing. For example trying to switch profiles or select skins. Also, XIV_DataBar is invisible when attached to the top of the screen.
![wowscrnshot_090417_210433](https://user-images.githubusercontent.com/31639376/30042105-ccc32c14-91b4-11e7-94b0-5cb33cda394d.jpg)

**Comment by ProfessionalGeek** [comment]
**Ace3** is a library framework used to build add-ons, and many add-ons bundle versions of this library with their own add-on to ensure compatibility. The one downside of something like that is when a big patch comes out, sometimes libraries and frameworks break... in this case the depreciated **PlaySound()** function has broken.

So even when the framework itself is updated ([which it has been](https://mods.curse.com/addons/wow/ace3)), the individual add-ons (TomTom, Bagnon, DBM, etc.) need to be updated to incorporate those changes. To be clear, this is nothing to do with DiabolicUI, and everything to do with other addons, as DiabolicUI has had the PlaySound() error fixed for months, well before 7.3.

Goldpaw has gone to the trouble of creating an add-on specifically to address the PlaySound() errors, [you can find that here](https://mods.curse.com/addons/wow/276930-playsoundfix). Give it a shot and see how you fare.

**Comment by goldpaw** [comment]
This is indeed an Ace3 bug, or the same bug in other addons that aren't updated to the 7.3.0 patch yet. It's not related to my UI, since that's been ready for the patch for months! ;) 

I don't recommend my playsound fix, because it causes as many problems as it solves. I wrote it mainly to get stuff working at all after the patch, but once other addon developers catch up, that playsound fix has to be removed! :o 

Having that said, try installing the standalone version of Ace3 instead. That will in most cases make sure that the most recent up-to-date version of Ace3 (without the PlaySound bugs) is loaded, as it will overwrite the older versions embedded in the various addons. And thus fix many, many, many of the patch problems! :)

Ace3 is on curse: 
https://mods.curse.com/addons/wow/ace3
